### ISSUE TITLE
Heroku deployment problems with memcache driver

### ISSUE THREAD

**Issue by blackknight467** [tedious/TedivmStashBundle#71]
So i'm trying to deploy to heroku using the memcache driver but I keep getting an exception when I attempt deployment.
```
remote:          [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
remote:          Unrecognized option "Memcache" under "stash.caches.default" 
```

The deploy works perfectly fine if if I change the driver back to FileSystem and the memcache configuration works just fine in my dev environment.  

Here is my config file:
```
stash:
    caches:
    # The default cache should be used with care. Consider adding another cache
    # pool for something specific used in many places.
        default:
            drivers: [ Memcache ]
            Memcache:
                servers:
                    - { server: %memcache_server%, port: 11211, weight: 1 }
        oauth:
            drivers: [ Memcache ]
            Memcache:
                prefix_key: oauth_
                servers:
                    - { server: %memcache_server%, port: 11211, weight: 1 }
            registerDoctrineAdapter: true
```
