### ISSUE TITLE
Unrecognized option "Apc" under "stash.caches.default"

### ISSUE THREAD

**Issue by layanto** [tedious/TedivmStashBundle#91]
With this in config.yml:
```
stash:
    drivers: [ Apc ]
    registerDoctrineAdapter: true
    Apc:
        namespace: sf_stash_
```

When doing app/console cache:clear with Symfony 2.8.1, getting this error:
Unrecognized option "Apc" under "stash.caches.default"
